### ISSUE TITLE
Upgrade from boto3 1.9.x to 1.10.x , 0.1.8 is not working anymore

### ISSUE THREAD

**Issue by yxd-hde** [HDE/python-lambda-local#54]
> It seems that since the upgrade from boto3 1.9.x to 1.10.x the newest version of python-lambda-local (0.1.8) is not working anymore.

Requested by some user.

**Comment by peamy** [comment]
On boto3 1.10.07:
```
$ python-lambda-local
Traceback (most recent call last):
  File "/home/nn-admin/.local/bin/python-lambda-local", line 5, in <module>
    from lambda_local import main
  File "/home/nn-admin/.local/lib/python3.6/site-packages/lambda_local/__init__.py", line 12, in <module>
    from .main import run
  File "/home/nn-admin/.local/lib/python3.6/site-packages/lambda_local/main.py", line 25, in <module>
    urllib3.disable_warnings()
AttributeError: module 'botocore.vendored.requests.packages.urllib3' has no attribute 'disable_warnings'
```

On boto3 1.9.253 python-lambda-local still seems to work.

**Comment by dthauvin** [comment]
i think this is why : 

https://github.com/boto/botocore/pull/1829

https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/
